import { useLayoutEffect, useRef } from "react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import CTA from "../CTA.jsx";

gsap.registerPlugin(ScrollTrigger);

const stats = [{ value: "₹50L", label: "Max Investment/FY" }, { value: "5yr", label: "Lock-in Period" }, { value: "5.25%", label: "Current Interest" }, { value: "100%", label: "Tax Exemption" }];
const process = [{ step: "Eligibility Check", desc: "We verify your capital gains from property sale and confirm eligibility under Section 54EC within the 6-month window." }, { step: "Bond Selection", desc: "We recommend bonds from NHAI, REC, PFC, or IRFC based on availability, yield, and your investment timeline." }, { step: "Application & Allotment", desc: "We handle the entire application process — form filling, cheque/RTGS, and follow-up until allotment confirmation." }];
const benefits = ["Complete capital gains tax exemption under 54EC", "Government-backed issuers (NHAI, REC, PFC, IRFC)", "Fixed interest income during lock-in period", "No market risk — guaranteed returns", "Interest credited annually to bank account"];
const audience = ["Property sellers with long-term capital gains", "Real estate investors seeking tax deferral", "HNIs looking for safe post-sale parking", "NRIs selling India property and needing 54EC"];
const features = ["NHAI Bonds", "REC Capital Gain Bonds", "PFC 54EC Bonds", "IRFC Tax-Free Bonds"];

const CapitalGainBonds = () => {
    const mainRef = useRef(null);
    useLayoutEffect(() => { window.scrollTo(0, 0); let ctx = gsap.context(() => { gsap.from(".detail-hero-text", { y: 60, opacity: 0, duration: 1, ease: "power4.out", stagger: 0.1 }); mainRef.current.querySelectorAll(".animate-section").forEach((el) => { gsap.from(el, { y: 40, opacity: 0, duration: 0.8, ease: "power3.out", scrollTrigger: { trigger: el, start: "top 85%" } }); }); }, mainRef); return () => ctx.revert(); }, []);

    return (
        <div ref={mainRef} className="w-full bg-white text-slate-900">
            <section className="relative h-[50vh] md:h-[40vh] flex items-center justify-center bg-slate-900 overflow-hidden"><img src="https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=1920" alt="" className="absolute inset-0 w-full h-full object-cover brightness-[0.25]" />
                <div className="absolute inset-0 bg-gradient-to-t from-slate-900/90 via-slate-900/50 to-slate-900/70" /><div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-red-600/10 rounded-full blur-[150px]" /><div className="relative z-10 text-center px-6"><p className="detail-hero-text text-sm uppercase tracking-[0.3em] text-red-400 font-semibold mb-4">Capital Gain Bonds</p><h1 className="detail-hero-text text-4xl md:text-7xl font-bold text-white tracking-tight">Save Tax on Property Sale</h1><p className="detail-hero-text mt-6 text-white/50 text-lg max-w-xl mx-auto font-light">Section 54EC bonds to get complete capital gains tax exemption on property transactions.</p></div></section>

            <section className="py-24 px-6"><div className="animate-section max-w-4xl mx-auto"><p className="text-sm uppercase tracking-[0.3em] text-red-600 font-semibold mb-4">Overview</p><h2 className="text-3xl md:text-4xl font-bold tracking-tight mb-8">About Capital Gain Bonds</h2><p className="text-gray-500 text-lg leading-relaxed font-light">When you sell property and earn long-term capital gains, Section 54EC allows you to invest up to ₹50 lakhs in specified bonds within 6 months to claim complete tax exemption. We help you navigate the application window, choose the right issuer, and ensure timely allotment before the deadline.</p></div></section>
            <section className="py-20 px-6 bg-[#fafafa]"><div className="animate-section max-w-5xl mx-auto"><div className="text-center mb-12"><p className="text-sm uppercase tracking-[0.3em] text-red-600 font-semibold mb-4">Categories</p><h2 className="text-3xl md:text-4xl font-bold tracking-tight">Bond Issuers</h2></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{features.map((f, i) => (<div key={i} className="bg-white rounded-2xl p-6 text-center border border-gray-100 hover:border-red-100 hover:shadow-md transition-all duration-300"><span className="text-red-600 font-bold text-2xl block mb-3">0{i + 1}</span><span className="text-sm font-medium text-slate-700">{f}</span></div>))}</div></div></section>
            <section className="py-24 px-6"><div className="animate-section max-w-5xl mx-auto"><div className="text-center mb-16"><p className="text-sm uppercase tracking-[0.3em] text-red-600 font-semibold mb-4">Process</p><h2 className="text-3xl md:text-4xl font-bold tracking-tight">How It Works</h2></div><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{process.map((p, i) => (<div key={i}><div className="w-12 h-12 bg-red-600 rounded-full flex items-center justify-center text-white font-bold text-lg mb-5">{i + 1}</div><h3 className="text-xl font-bold mb-2">{p.step}</h3><p className="text-gray-500 font-light leading-relaxed">{p.desc}</p></div>))}</div></div></section>
            <section className="py-24 px-6 bg-[#fafafa]"><div className="max-w-4xl mx-auto"><div className="animate-section mb-10"><p className="text-sm uppercase tracking-[0.3em] text-red-600 font-semibold mb-4">Benefits</p><h2 className="text-3xl md:text-4xl font-bold tracking-tight">What You Get</h2></div><ul className="space-y-4">{benefits.map((b, i) => (<li key={i} className="flex items-start gap-4 p-5 bg-white rounded-2xl border border-gray-100"><span className="w-8 h-8 bg-red-600 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5"><svg className="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="3"><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg></span><span className="text-slate-700 text-lg font-light">{b}</span></li>))}</ul></div></section>
            <section className="py-24 px-6"><div className="animate-section max-w-4xl mx-auto"><p className="text-sm uppercase tracking-[0.3em] text-red-600 font-semibold mb-4">Ideal For</p><h2 className="text-3xl md:text-4xl font-bold tracking-tight mb-10">Who Is This For?</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{audience.map((a, i) => (<div key={i} className="flex items-center gap-4 p-5 bg-[#fafafa] rounded-2xl border border-gray-100"><span className="w-10 h-10 bg-slate-900 rounded-full flex items-center justify-center flex-shrink-0"><svg className="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2"><path strokeLinecap="round" strokeLinejoin="round" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" /></svg></span><span className="text-slate-700 font-light">{a}</span></div>))}</div></div></section>
            <CTA title="Sold a property recently?" subtitle="Book a free consultation with our capital gains tax experts today." secondaryTo="/services" />
        </div>
    );
};
export default CapitalGainBonds;
